name: Kitsu API Deployment

on: [deployment]

env:
  SENTRY_ORG: kitsu
  SENTRY_PROJECT: server
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_TOKEN }}

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: sudo snap install yq

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.SENKO_SAN_KEY }}
        repository: hummingbird-me/kitsu-ops
        path: ops

    - name: Configure Git
      working-directory: ops
      run: |
        git config user.name "Senko-san"
        git config user.email "developers@kitsu.app"

    - name: Update Image Version
      working-directory: ops
      run: ./kubernetes/apps/kitsu-api/bin/update.sh staging ${GITHUB_SHA::8}

    - name: Push to Github
      working-directory: ops
      run: git push
