name: Validate Schema Changes

on:
  workflow_run:
    workflows: ["Kitsu Test Suite"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "Kitsu Test Suite"
          workflow_conclusion: success
          run_id: ${{github.event.workflow_run.id}}
          name: graphql-schema-ruby-3.1

      - name: Display structure of downloaded files
        run: ls -R

      - name: Validate Schema Changes
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'schema.graphql'
          endpoint: 'https://kitsu.app/api/graphql'
